### ISSUE TITLE
The docson CSS could do with a bit of artistry

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#15]
Looking at the [docson rendering of the invoice schema](http://ausdigital.org/docson.html#https://raw.githubusercontent.com/ausdigital/billing-semantics/master/spec/v1.0.0/Invoice.json) I think it could use a little more prettiness...

Some ideas in the attached marked up screenshot.  But please feel free to suggest your own.
![docson-presentationimprovements](https://cloud.githubusercontent.com/assets/13426392/21909268/488c9dce-d96b-11e6-8364-3638068f7a64.png)

**Comment by monkeypants** [comment]
what if the 'signature-header' class was a grey background (when the box is expanded)?

**Comment by webilhan** [comment]
@onthebreeze @kshychko I made changes. I found that box header with description was hidden in CSS, commented it, so now it is shown. Please merge and review.

**Comment by onthebreeze** [comment]
There's still two problems:

* One looks like a bug - the expand/collapse icon next to "note" seems to affect the whole document instead of just the note element.  In fact, it shouldnt have an expand/collapse at all because it's just a simple string so there is no corresponding complex type to view.
* The elements that are defined by a complex type (like invoiceLine) are confusing to view.  I think the name of the type is redundant on the line when it already appears on the box title below the line when expanded.  So lets just make the action simpler - highlight elements that a re defined by a complex type so that it's obvious that when I click on them I will see an expanded definition below.

See attached screenshot
![docsonviewer-remainingbugs](https://cloud.githubusercontent.com/assets/13426392/21958590/c6a9fc7e-db05-11e6-99bb-3a8b744a68e5.png)

**Comment by webilhan** [comment]
@onthebreeze Please check now.

**Comment by onthebreeze** [comment]
ok much better.
