### ISSUE TITLE
rename repositories and test / fix all links according to consistent convention.

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#19]
Every specification has a unique and specific short name as defined on the left hand panel at ausdigital.org.  For example "dcl" = "digital capability locator".    We have been a little inconsistent in the naming of repos, read-the-docs etc so far and need to fix it now.  

* rename all repos with just the spec short name (eg "dcl").  Exception is the repo for the ausdigital website that will remain "ausdigital.gothub.io".
* the title of all repos will be "Ausdigital <spec full name> specification" (eg "Ausdigital digital capability locator specification")
* the readthedocs.io generated site for each specification will have the form "asudigital-<spec>.readthedocs.io" (eg ausdigital-dcl.readthedocs.io).  this is to ensure uniqueness in RTD subdomain.
* the URL for every repo will link to the latest readthedocs.

Once the repos are renamed, we need to fix all links in the documentation and the ausdigital.org site.

**Comment by monkeypants** [comment]
I fully agree with ausdigital-<acronym> for doc names (e.g. `ausdigital-dcl.readthedocs.io`). But I think just using the acronym for the repo names is no good. When someone forks it, they will loose the organisation context. So the name needs to provide more context than just an acronym.

ausdigital/ausdigital-foo is no good either though (repetition is noise). ausdigital/digital-capability-locator seems like the best style of repo name.

**Comment by kshychko** [comment]
ausdigital/ausdigital-foo seems to be OK for me, it affects only github interface.
'ausdigital-dcl' seems to be more clearer than 'digital-capability-locator' - we get both a short specification name (dcl) and organisation context (ausdigital)

**Comment by monkeypants** [comment]
OK, you convinced me. Let's go with consistency:
 * ausdigital/ausdigital-foo for the repo names
 * ausdigital-foo.readthedocs.io for the spec publication

**Comment by monkeypants** [comment]
rtd updated:
* ausdigital-dcl.readthedocs.io
* ausdigital-idp.readthedocs.io
* ausdigital-dcp.readthedocs.io
* ausdigital-tap.readthedocs.io
* ausdigital-tap-gw.readthedocs.io
* ausdigital-nry.readthedocs.io

fixed http://ausdigital.org links too, various README references and so on. We now need to go through all the specs and fix references/links in the content too.

**Comment by kshychko** [comment]
All specification repositories have been renamed and updated except superannuation-semantics
and ordering-semantics.
The references/links in the content are fixed too.

**Comment by onthebreeze** [comment]
may as well do those as well

* ausdigital-order
* ausdigital-ship
* ausdigital-super

They are empty and un-claimed but may as well have them ready... ;)

**Comment by kshychko** [comment]
renamed to ausdigital-order and ausdigital-super, ausdigital-ship name has been already applied.

**Comment by kshychko** [comment]
rtd needs to be updated:

- billing-semantics.readthedocs.io -> https://ausdigital-bill.readthedocs.io 
- code-lists.readthedocs.io -> https://ausdigital-code.readthedocs.io
- ubl-json.readthedocs.io -> https://ausdigital-json.readthedocs.io

rtd missing:
-  https://ausdigital-ship.readthedocs.io
-  https://ausdigital-order.readthedocs.io
-  https://ausdigital-super.readthedocs.io

**Comment by monkeypants** [comment]
The 3 rtd updates are done (ausdigital-bill, ausdigital-code and ausdigital-json). The 3 new semantics sites are stubbed out (ausdigital-ship, ausdigital-order and ausdigital-super).

the semantics specs are only stubs.

**Comment by monkeypants** [comment]
looks like we can close this now - do you agree @onthebreeze? @kshychko?

**Comment by kshychko** [comment]
I do, we can close the issue.
