### ISSUE TITLE
The left hand navigation panel does not scroll on mobile devices.

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#20]
When opening the ausdigital.org homepage on a mobile device, the left hand navigation panel is presented when the user clicks the navbar icon.  Thats good - but it's now too long and goes off the bottom of the page - so links near the bottom cant be accessed from mobile devices.

**Comment by koriaf** [comment]
Also, I think it's trivial for Illya to alter css to make it easy printable - just hide left menu and expand content area on full page with. Theoretically useful and just looks good.

**Comment by webilhan** [comment]
@onthebreeze Menu fixed, now links near the bottom can be accessed from mobile devices
@koriaf Printable version adjusted.
