### ISSUE TITLE
Minor markup problems

### ISSUE THREAD

**Issue by krylataya** [ausdigital/ausdigital.github.io#28]
![21](https://cloud.githubusercontent.com/assets/10355630/22299126/70046ad2-e33c-11e6-8d40-4eaaa2ae696f.jpg)

![2](https://cloud.githubusercontent.com/assets/10355630/22299087/482377f6-e33c-11e6-8c7b-ceb1d1938723.jpg)

![1](https://cloud.githubusercontent.com/assets/10355630/22299037/1336883a-e33c-11e6-9319-84a8a3684955.jpg)

**Comment by kshychko** [comment]
@webilhan, please make sure it will be fixed with a new design applied.

**Comment by webilhan** [comment]
@krylataya Because we created new design. I think this ticket could be closed.

**Comment by monkeypants** [comment]
agree
