### ISSUE TITLE
Broken swaggerhub links

### ISSUE THREAD

**Issue by krylataya** [ausdigital/ausdigital.github.io#30]
UBL-XML page:
UBL XML 1.0 API - https://app.swaggerhub.com/api/ausdigital/ausdigital-ubl-xml/1.0.0 - "Sorry, we can't find ausdigital / ausdigital-ubl-xml / 1.0.0"

Billing process page:
Billing 1.0 API - https://app.swaggerhub.com/api/ausdigital/ausdigital-bill/1.0 - "Sorry, we can't find ausdigital / ausdigital-bill / 1.0"

**Comment by kshychko** [comment]
fixed, @krylataya , please verify

**Comment by krylataya** [comment]
@kshychko is it OK that link on Billing process page goes to ubl-json api https://app.swaggerhub.com/api/ausdigital/ausdigital-ubl-json/1.0
?

**Comment by kshychko** [comment]
yes, we have a single endpoint for transformation and validation API
with the latest renaming the url has been changed to https://app.swaggerhub.com/api/ausdigital/ausdigital-syn/1.0

**Comment by krylataya** [comment]
ok, issue closed
