### ISSUE TITLE
Need a rigorous spec naming convention

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#32]
I dont think this needs a separate spec in itself but we do need a paragraph somewhere about naming conventions for spec versions.

Suggest something like 

```
<github repo name>/<v.major.minor>  for example
ausdigital-idp/v.1.0
```

**Comment by onthebreeze** [comment]
And we need to be clear how these names map to the various ubl/dcp data elements such as

* in the UBL semantics;
  * Schema Reference (handled differently in XML and JSON but same intent)
  * customizationID
  * profileID
* in the DCP semantics;
  * DocumentIdentifier
  * ProcessIdentifier
  * TransportProfile

I think a separate page on ausdigital.org that is all about identifiers will cover this need.

**Comment by monkeypants** [comment]
I think a separate spec/repo would be OK for this. AusDigital specification naming specification, `ausdigital-name/1`

Also, there are probably places where we want to say things like "as per `ausdigital-foo/1+`, meaning anything in SemVer 1.x.x or later. I'm not convinced we will often need the full SemVer granularity, but it's probably an efficient way to outsource the details.

**Comment by monkeypants** [comment]
This is done
