### ISSUE TITLE
Highlight left menu item when a corresponding spec is open

### ISSUE THREAD

**Issue by kshychko** [ausdigital/ausdigital.github.io#36]
As now we render a spec as a part of ausdigital.org content, it would be good to highlight a corresponding left menu item, so user will not be confused that he left the current specification section.
Please take into account, that specification id (ausdigital-foo) is included into the path to a spec. For example:

http://ausdigital.org/ausdigital-idp/

and 

http://ausdigital.org/specs/ausdigital-idp/1.0/

**Comment by webilhan** [comment]
@kshychko Done

**Comment by kshychko** [comment]
verified
