### ISSUE TITLE
Add anchor elements to generated spec headings

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#38]
We often want to refer to a specific paragraph in a spec from another spec.  Currently there are no heading /  subheading level HTML anchors in the generated specs 

Please add so that we can have more targeted references

**Comment by webilhan** [comment]
@onthebreeze I have added icon which will be shown when you hover on the heading and there you can copy link with anchor to this section. Will this way work for you, see for example - http://ausdigital.org/specs/ausdigital-dcp/1.0/

**Comment by onthebreeze** [comment]
that's perfect thanks
