### ISSUE TITLE
add examples to the API specs

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#40]
API docs like http://ausdigital.org/specs/ausdigital-dcp/1.0/api are nice but seem to be missing important information about the request/response body.

Need to add examples - something like https://jexhson.github.io/jekyll-swagger/example-1.html

**Comment by kshychko** [comment]
@webilhan , could you please adjust the layout for a box with an example?
![digital capability publisher dcp interface specification ausdigital standards by ausdigital 2](https://cloud.githubusercontent.com/assets/6890602/24831668/d2f6c7ae-1ca6-11e7-9742-2d3c3a2c299c.png)

**Comment by webilhan** [comment]
@kshychko Layout adjusted please check.

**Comment by kshychko** [comment]
@webilhan , thanks! Looks OK now!

**Comment by kshychko** [comment]
@webilhan , please add a render of example property which is located in the request parameter.
So if the request parameter has "example" property, render its value.
For responses it is a text, but for requests it is JSON object, although should be treated as a text.

Example below:

```
"keyDetailPost": {
      "properties": {
        "pubKey": {
          "type": "string"
        },
        "revoked": {
          "type": "string",
          "format": "date-time"
        },
        "fingerprint": {
          "type": "string"
        }
      },
      "example": {
        "published": "2017-04-11T13:58:37.058Z",
        "keyid": "string",
        "pubKey": "string",
        "revoked": "2017-04-11T13:58:37.058Z",
        "fingerprint": "string"
      }
    }
```

**Comment by webilhan** [comment]
@kshychko Render of example property in the request parameter has been added.

**Comment by kshychko** [comment]
thanks! works well!
Could you please also check why tags are not shown for the three of five methods in DCL spec - http://ausdigital.org/specs/ausdigital-dcl/1.0/api#

**Comment by webilhan** [comment]
@kshychko Tags showing fixed.

**Comment by kshychko** [comment]
verified as fixed, thanks!

**Comment by kshychko** [comment]
tags are now being duplicated:
http://ausdigital.org/specs/ausdigital-dcp/1.0/api

**Comment by webilhan** [comment]
@kshychko Fixed.

**Comment by kshychko** [comment]
verified as fixed
