### ISSUE TITLE
Need a "sign-up here" hint everywhere we have a link to a slack channel

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#44]
We have a self-service slack sign up here - https://chat.ausdigital.org/
And we have a number of links to the relevant slack channels in the specs - for example here - http://ausdigital.org/ausdigital-dcp/ (DCP Slack channel link).

BUT - it's not obvious enough (when you are on a spec page) that you need to sign up to the ausdigital slack team first.  

Please add a "signup to our slack team" link next to each slack channel link on each spec page..

**Comment by kshychko** [comment]
the links have been added, closing the issue.
