### ISSUE TITLE
Tidy up swagger specification presentation

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital.github.io#47]
The swagger specifications that are published for each specification - eg this one http://swagger.testpoint.io/?url=http://ausdigital.org/specs/ausdigital-dcp/1.0/swagger.json for DCP - could use some tidying up.

Especially the sample data structures - see screenshot.  
![swagger ui](https://user-images.githubusercontent.com/13426392/27030371-4f540542-4faf-11e7-9a57-a3abbbf92f31.png)

**Comment by kshychko** [comment]
swagger document format has been changed from json to yaml - easier to maintain and clean examples. closing the issue.
